_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.8.13
        t:
            "1":
                - 1
                - 9
                - 41
                - 51
                - 55
            "2":
                - 1
                - 9
                - 41
                - 51
                - 55
            "3":
                - 2
                - 23
                - 55
            "4": 3.8.13
            "5": 0.19.11
            "8":
                - 5
            "10":
                - 22
            "12": 0.19.11
            "13": linux-x86_64
learning_rate:
    value: 0.0005
weight_decay:
    value: 0.0002
